version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: accounting-postgres
    environment:
      POSTGRES_DB: accounting
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "9001:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./data/init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - account

networks:
  account:
    driver: bridge
