spring:
  application:
    name: accounting

  # JPA/Hibernate 설정
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: account

  # 데이터소스 설정
  datasource:
    url: jdbc:postgresql://localhost:9001/accounting?currentSchema=account
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

# 로깅 설정
logging:
  level:
    com.jinnara.accounting: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# 서버 설정
server:
  port: 8080
